# Lab 1 - biblioteka NumPy

NumPy (https://numpy.org) to jedna z najpopularniejszych bibliotek języka Python
przeznaczona do obliczeń numerycznych na tensorach w formie tablic.

## Instalacja

W celu instalacji pakietu NumPy należy wpisać
w terminalu polecenie **pip install numpy**

## Import biblioteki

Bibliotekę NumPy, podobnie jak każdy inny zewnętrzny pakiet, należy zaimportować.
Służy do tego instrukcja import. Dobrą praktyką jest importowanie biblioteki NumPy z aliasem np,
co można zapisać następująco:

In [3]:
import numpy as np

## Tworzenie nowych tablic na podstawie list

Najprostszą metodą utworzenia tablicy NumPy jest przekazanie listy wartości do funkcji array z pakietu NumPy:

In [4]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


W podobny sposób można tworzyć również tablice wielowymiarowe (tensory).
W tym celu należy przekazać do funkcji array z pakietu NumPy listę wielowymiarową.

In [5]:
arr_2d = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
])

arr_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

## Typy danych w NumPy

Typy danych w bibliotece NumPy definiują charakter wartości przechowywanych w tablicach.
Typ może zostać ustalony automatycznie bądź wskazany manualnie (w celu optymalizacji pamięci) za pomocą parametru dtype.

In [6]:
arr_int = np.array([1, 2, 3, 4, 5], dtype='i')

arr_int

array([1, 2, 3, 4, 5], dtype=int32)

Typ wartości w tablicy można sprawdzić za pomocą atrybutu dtype.

In [7]:
arr_int.dtype


dtype('int32')

### Podstawowe typy danych w NumPy

Wyróżniany następujące podstawowe typy danych występujące w bibliotece NumPy

- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string
- V - fixed chunk of memory for other type (void)

### Złożone typy danych w NumPy

W typie danych można również wskazać ilość zarezerwowanego miejsca na wartość.
Przykładowo, "i4" oznacza typ integer (całkowitoliczbowy) 4-bajtowy.

In [8]:
arr = np.array([1, 2, 3, 4, 5], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


## Tworzenie tablic przy użyciu funkcji numpy

Pakiet NumPy umożliwia również tworzenie tablic wypełnionych wartościami.

Funkcja zeros służy do tworzenia tablic o wskazanym rozmiarze, wypełnionych zerami:

In [9]:
np.zeros(10, dtype='i')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

Funkcji zeros można również użyć do tworzenia tablic wielowymiarowych:

In [10]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Bardzo podobne zastosowanie ma funkcja ones, która tworzy tablice wypełnione jedynkami:

In [11]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Do stworzenia przestrzeni liniowej o wskazanym zakresie i liczbie elementów należy użyć funkcji linspace

In [12]:
np.linspace(0, 10, 6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

Funkcja eye utworzy macierz jednostkową (kwadratową) o wskazanym rozmiarze:

In [13]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Za pomocą funkcji rand pochodzącej z modułu random w pakiecie NumPy
można wygenerować tensor o wskazanym rozmiarze zawierający wartości losowe
pochodzące z rozkładu normalnego jednorodnego, w przedziale [0-1):

In [14]:
np.random.rand(5)


array([0.06776932, 0.7611549 , 0.37923355, 0.11677356, 0.8588277 ])

In [15]:
np.random.rand(3, 2)

array([[0.57793401, 0.55913358],
       [0.73059754, 0.809417  ],
       [0.71326697, 0.55260254]])

Funkcja randn pochodząca z modułu random w pakiecie NumPy ma podobne zastosowanie do funkcji rand.
Różnica między nimi polega na generowaniu wartości losowych pochodzących z rozkładu normalnego:

In [16]:
np.random.randn(5, 5)


array([[ 1.11244161,  1.76990654, -1.5821982 ,  0.72993805, -0.81371237],
       [-0.79454934,  0.69663145,  1.38312112, -0.05436593, -1.03625577],
       [-0.34795293, -0.84789399, -1.13722568,  0.75970198, -0.50499415],
       [ 1.87599717,  0.49381141, -0.18172553,  1.30819631,  0.32262407],
       [ 0.51908122, -0.74579121,  0.76406798, -0.05386557,  1.29445669]])

Funkcja randint pochodząca z modułu random w pakiecie NumPy ma również podobne zastosowanie do swoich poprzedniczek.
Różnica polega na generowaniu wartości losowych z wyznaczonych przedziałów:

In [17]:
np.random.randint(1, 49, (3, 6))

array([[ 8, 38, 20, 12, 22, 30],
       [17, 26,  9, 23, 47, 40],
       [14, 16, 47, 33, 21,  5]])

## Indeksowanie danych w tablicach

Biblioteka NumPy umożliwia wygodne wybieranie wartości znajdujących się w tablicach za pomocą wskazania ich pozycji.

In [18]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

Wiersz z takiej tablicy można pobrać wskazując jego indeks:

In [19]:
arr_2d[0]

array([ 5, 10, 15])

Wartośc skalarną można pobrać wskazując jej konkretną pozycję w formacie [wiersz, kolumna]:

In [20]:
arr_2d[1, 2]


30

Kolumnę z tablicy można pobrać wskazując wszystkie wiersze za pomocą znaku : oraz indeks kolumny w następującym formacie [:, col]:

In [21]:
arr_2d[:, 1]

array([10, 25, 40])

Za pomocą indeksu -1 można pobrać ostatnią wartość we wskazanym wymiarze:

In [22]:
arr_2d[-1, -1]

45

Biblioteka NumPy umożliwia również pobieranie podtablic za pomocą zakresów indeksów wskazanych w konkretnych wymiarach:

In [23]:
matrix = np.random.randint(1, 100, (5, 5))

matrix

array([[88, 88, 87, 46, 63],
       [62, 84, 77, 78, 64],
       [ 5, 29, 66, 85, 14],
       [64, 76, 81, 56, 94],
       [86,  7, 79, 61, 81]])

In [24]:
matrix[1:4, 1:4]

array([[84, 77, 78],
       [29, 66, 85],
       [76, 81, 56]])

## Kształt tablicy i jego modyfikacja

Kształt tablicy można sprawdzić za pomocą atrybutu shape:

In [25]:
arr = np.ones((5, 4))

print(arr)

arr.shape

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


(5, 4)

Wynik (5, 4) informuje nas o 5 wierszach i 4 kolumnach macierzy.

Za pomocą funkcji reshape można zmodyfikować kształt tablicy.

In [26]:
arr = np.ones(25)

arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1.])

In [27]:
arr.reshape((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## Wyszukiwanie w tablicach wartości największych i najmniejszych

In [28]:
arr = np.random.randint(1, 100, 10)

arr

array([50, 75, 40, 75, 74, 62, 48, 10, 19, 62])

Za pomocą metody min można znaleźć wartość największą:

In [29]:
arr.min()


10

Wartość największą można znaleźć za pomocą metody max:

In [30]:
arr.max()

75

Pozycję elementu o największej lub najmniejszej wartości można znaleźć za pomocą metod argmax i argmin:

In [31]:
print(f'wartosc najwieksza: {arr.max()}, pozycja wartosci najwiekszej: {arr.argmax()}')
print(f'wartosc najmniejsza: {arr.min()}, pozycja wartosci najmniejszej: {arr.argmin()}')

wartosc najwieksza: 75, pozycja wartosci najwiekszej: 1
wartosc najmniejsza: 10, pozycja wartosci najmniejszej: 7


## Funkcje matematyczny w NumPy

Pakiet NumPy dostarcza wiele funkcji matematycznych dokonujących operacji na wszystkich elementach tablic.

In [32]:
arr = np.arange(11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Za pomocą funkcji sqrt można obliczyć pierwiastki kwadratowe wszystkich elementów znajdujących się w tablicy:

In [33]:
np.sqrt(arr)


array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

Za pomocą funkcji exp można wyznaczyć wartość wyrażenia $$e ^ x$$ gdzie x to każdy kolejny element znajdujący się w tablicy:

In [34]:
np.exp(arr)


array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

## Arytmetyka i algebra tablic

Pakiet NumPy umożliwia również wygodne dokonywanie działań arytmetycznych oraz algebraicznych na tablicach:

In [35]:
arr0 = np.random.randint(1, 10, (3, 3))
arr1 = np.random.randint(1, 10, (3, 3))

arr0, arr1

(array([[4, 6, 2],
        [8, 2, 9],
        [9, 9, 7]]),
 array([[3, 1, 6],
        [9, 1, 2],
        [3, 8, 7]]))

Działań arytmetycznych na tablicach można dokonać za pomocą klasycznych operatorów arytmetycznych:

In [36]:
arr0 + arr1

array([[ 7,  7,  8],
       [17,  3, 11],
       [12, 17, 14]])

In [37]:
arr0 - arr1

array([[ 1,  5, -4],
       [-1,  1,  7],
       [ 6,  1,  0]])

In [38]:
arr0 * arr1

array([[12,  6, 12],
       [72,  2, 18],
       [27, 72, 49]])

In [39]:
arr0 ** 2

array([[16, 36,  4],
       [64,  4, 81],
       [81, 81, 49]])

Pakiet NumPy udostępnia również interfejs do dokonywania operacji algebraicznych na tensorach.

Do wyznaczenia iloczynu skalarnego dwóch tensorów służy metoda dot:

In [40]:
arr0.dot(arr1)


array([[ 72,  26,  50],
       [ 69,  82, 115],
       [129,  74, 121]])

In [41]:
arr0[0].dot(arr1[1])


46

## Zadania

1. Utworzyć tablicę zawierającą 50 piątek
2. Utworzyć tablicę o rozmiarze 5x5 z wartościami od 1 do 25
3. Utworzyć tablicę tablicę liczb parzystych od 10 do 50
4. Utworzyć macierz, w której na przekątnej znajdą się wartości równe 8, a pozostałe będą wynosiły 0
5. Utworzyć tablicę o rozmiarze 10x10 z wartościami zwiększającymi się o 0.01
6. Utworzyć przestrzeń liniową 50 wartości z zakresu 0-1
7. Wybrać podtablicę 12-elementową, z tablicy utworzonej w zadaniu 2, z wartościami w zakresie 12-25
8. Wybrać 3 pierwsze elementy z ostatniej kolumny tablicy utworzonej w zadaniu 2, a następnie ułożyć z nich kolumnę
9. Wyznaczyć sumę wartości elementów znajdujących się w dwóch ostatnich wierszach macierzy utworzonej w zadaniu 2
10. Przygotować skrypt, który stworzy tensor zawierający losowe wartości całkowite, losowym wymiarze i losowym rozmiarze każdego z wymiarów